### ISSUE TITLE
Rodar Aplicação no Tomcat

### ISSUE THREAD

**Issue by schirrel** [algaworks/ebook-javaee#1]
Oi, cabei de baixar o livro não consigo fazer a aplicação 'subir' no tomcat.
Clonei o repositório e to usando Tomcat 8.5
Eu importei o projeto no STS, fiz clean install e apos isso fiz 'Update Maven Project' e novamente clean install.
A mensagem de erro é a seguinte:
```
A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/Financeiro]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:941)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:872)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1421)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1411)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/Financeiro]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	... 6 more
Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-000123: Error loading com.algaworks.financeiro.util.TransactionInterceptor defined in <class>com.algaworks.financeiro.util.TransactionInterceptor</class> in file:/C:/JavaEE/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/Financeiro/WEB-INF/classes/META-INF/beans.xml@9
	at org.jboss.weld.bootstrap.enablement.GlobalEnablementBuilder$ClassLoader.apply(GlobalEnablementBuilder.java:315)
	at org.jboss.weld.bootstrap.enablement.GlobalEnablementBuilder$ClassLoader.apply(GlobalEnablementBuilder.java:302)
	at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:495)
	at java.util.AbstractList$Itr.next(AbstractList.java:358)
	at org.jboss.weld.bootstrap.enablement.GlobalEnablementBuilder.filter(GlobalEnablementBuilder.java:293)
	at org.jboss.weld.bootstrap.enablement.GlobalEnablementBuilder.createModuleEnablement(GlobalEnablementBuilder.java:239)
	at org.jboss.weld.bootstrap.BeanDeployment.createEnablement(BeanDeployment.java:219)
	at org.jboss.weld.bootstrap.WeldStartup.startInitialization(WeldStartup.java:381)
	at org.jboss.weld.bootstrap.WeldBootstrap.startInitialization(WeldBootstrap.java:76)
	at org.jboss.weld.environment.servlet.WeldServletLifecycle.initialize(WeldServletLifecycle.java:144)
	at org.jboss.weld.environment.servlet.EnhancedListener.onStartup(EnhancedListener.java:61)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5204)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.algaworks.financeiro.util.TransactionInterceptor
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1291)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
	at org.jboss.weld.environment.deployment.WeldResourceLoader.classForName(WeldResourceLoader.java:40)
	at org.jboss.weld.bootstrap.enablement.GlobalEnablementBuilder$ClassLoader.apply(GlobalEnablementBuilder.java:313)
	... 18 more
```

Não tenho muita experiencia com javaee

**Comment by jcjesus** [comment]
Olá @CoderSquirrel pela mensagem provável que o Spring não conseguiu fazer a injeção da classe com.algaworks.financeiro.util.TransactionInterceptor, pode ser devido a não conseguir baixar a dependência ou mesmo compilar o projeto. Reveja no livro o passo a passo para configurar o ambiente novamente.

Espero ter ajudado.

Atenciosamente,
Jesus
